### ISSUE TITLE
Bug on install pyroCMS "Composer install"

### ISSUE THREAD

**Issue by sandrobocon** [anomalylabs/dashboard-module#1]
It returns when try to install pyroCMS, BUT how it seems to be specific from this module, I thought it should be treated here.

So when the problem error show is:
~~~~
    # composer install
    Loading composer repositories with package information
    Installing dependencies (including require-dev)           
      - Installing anomaly/dashboard-module (dev-master cc8e11a)
        Cloning cc8e11ad825e9a5d20a4347283e141a107c31e8e
        cc8e11ad825e9a5d20a4347283e141a107c31e8e is gone (history was rewritten?)
        Failed to download anomaly/dashboard-module from source: Failed to execute git checkout 'cc8e11ad825e9a5d20a4347283e141a107c31e8e' && git reset --hard 'cc8e11ad825e9a5d20a4347283e141a107c31e8e'

    Note: checking out 'cc8e11ad825e9a5d20a4347283e141a107c31e8e'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b new_branch_name

    HEAD is now at cc8e11a... Redesigning
    error: unable to create file resources/js/highcharts/exporting-server/java/highcharts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classes/com/highcharts/export/controller/ZeroRequestParameterException.class (Operation not permitted)
    fatal: Could not reset index file to revision 'cc8e11ad825e9a5d20a4347283e141a107c31e8e'.

        Now trying to download from dist
      - Installing anomaly/dashboard-module (dev-master cc8e11a)
        Downloading: 100%         


                                                                                         
      [RuntimeException]                                                                 
      Could not delete core/anomaly/dashboard-module/7277cc9cf55089639d302d814c3caa30:
~~~~

The commit hash this time was '7277cc9...'  but it changes every time I try again.
I tried to get from a previous commit, but the error keeps the same.

**Comment by RyanThompson** [comment]
Thanks for the heads up! I will look into this immediately.


On Mar 13, 2015, at 11:14 AM, Sandro Boçon <notifications@github.com<mailto:notifications@github.com>> wrote:


It returns when try to install pyroCMS, BUT how it seems to be specific from this module, I thought it should be treated here.

So when the problem error show is:

    # composer install
    Loading composer repositories with package information
    Installing dependencies (including require-dev)
      - Installing anomaly/dashboard-module (dev-master cc8e11a)
        Cloning cc8e11ad825e9a5d20a4347283e141a107c31e8e
        cc8e11ad825e9a5d20a4347283e141a107c31e8e is gone (history was rewritten?)
        Failed to download anomaly/dashboard-module from source: Failed to execute git checkout 'cc8e11ad825e9a5d20a4347283e141a107c31e8e' && git reset --hard 'cc8e11ad825e9a5d20a4347283e141a107c31e8e'

    Note: checking out 'cc8e11ad825e9a5d20a4347283e141a107c31e8e'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b new_branch_name

    HEAD is now at cc8e11a... Redesigning
    error: unable to create file resources/js/highcharts/exporting-server/java/highcharts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classes/com/highcharts/export/controller/ZeroRequestParameterException.class (Operation not permitted)
    fatal: Could not reset index file to revision 'cc8e11ad825e9a5d20a4347283e141a107c31e8e'.

        Now trying to download from dist
      - Installing anomaly/dashboard-module (dev-master cc8e11a)
        Downloading: 100%



      [RuntimeException]
      Could not delete core/anomaly/dashboard-module/7277cc9cf55089639d302d814c3caa30:


The commit hash this time was '7277cc9...' but it changes every time I try again.
I tried to get from a previous commit, but the error keeps the same.

**Comment by sandrobocon** [comment]
Bug remains in alpha2.
Tried to remove and reinstall all pyrocms from git, but no success.

Just header changed on some update.

~~~
     - Installing anomaly/dashboard-module (dev-master 0398d13)
    Cloning 0398d1301148b9c3634efc58177c0cb32bc4826c
    0398d1301148b9c3634efc58177c0cb32bc4826c is gone (history was rewritten?)
... (all other things the same) ...
~~~

Any tip?

**Comment by RyanThompson** [comment]
This is on a fresh install? It really should not do this..

Try `composer clear-cache` and clone down new.

**Comment by sandrobocon** [comment]
Well some news.
It seems to be some folder permission mistake. I usually use a folder created by VM Virtual Box. It give this rules:
drwxrwx--- 1 root vboxsf
Reading again the error it's without permission to create .class on folder, as below:
~~~
...
HEAD is now at cc8e11a... Redesigning
    error: unable to create file resources/js/highcharts/exporting-server/java/highcharts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classes/com/highcharts/export/controller/ZeroRequestParameterException.class (Operation not permitted)
...
~~~

When I tried on another folder (outside of this), it seems composer create everything all right, but on this one not.
Others folders are created all right too, as 'installer-module', 'preferences-module', and many others installed before 'dashboard-module'.

I coundn't find out where exactly is the error, but I believe is some permission.

I know nothing about composer, i was introduced to it by pyrocms, I thing if I add the user that composer uses to install on group 'vboxsf' it should install.

Well that is it I discovered so far. Hope be usefull to find how fix it later.

For now I will be testing PyroCMS installing in a new folder, but for a production I will have some bkp problems.

Tks for all suport and fast answers!

**Comment by RyanThompson** [comment]
Glad you figured it out!

**Comment by jacksun101** [comment]
I just meet the same error. I use vagrant + laravel/homestead on my windows 8. 
How can I do anything about it? Thanks.

- - - - -

vagrant@homestead:/vagrant/code/pyrocms/alpha2$ composer install
Loading composer repositories with package information

vagrant@homestead:/vagrant/code/pyrocms/alpha2$ ls -al
total 42
drwxrwxrwx 1 vagrant vagrant 4096 May 26 08:59 .
drwxrwxrwx 1 vagrant vagrant    0 May 26 08:42 ..
drwxrwxrwx 1 vagrant vagrant    0 May 26 08:47 addons
drwxrwxrwx 1 vagrant vagrant    0 May 26 08:47 app
-rwxrwxrwx 1 vagrant vagrant 1635 May 26 08:47 artisan
drwxrwxrwx 1 vagrant vagrant 4096 May 26 09:13 bin
drwxrwxrwx 1 vagrant vagrant    0 May 26 08:47 bootstrap
-rwxrwxrwx 1 vagrant vagrant 1695 May 26 08:47 build.xml
-rwxrwxrwx 1 vagrant vagrant 3403 May 26 08:47 composer.json
drwxrwxrwx 1 vagrant vagrant 4096 May 26 08:47 config
-rwxrwxrwx 1 vagrant vagrant 2029 May 26 08:47 CONTRIBUTING.md
drwxrwxrwx 1 vagrant vagrant    0 May 26 09:17 core
drwxrwxrwx 1 vagrant vagrant    0 May 26 08:47 database
drwxrwxrwx 1 vagrant vagrant 4096 May 26 08:47 .git
-rwxrwxrwx 1 vagrant vagrant   12 May 26 08:47 .gitattributes
-rwxrwxrwx 1 vagrant vagrant   39 May 26 08:47 .gitignore
-rwxrwxrwx 1 vagrant vagrant  498 May 26 08:47 Gulpfile.js
-rwxrwxrwx 1 vagrant vagrant   98 May 26 08:47 package.json
-rwxrwxrwx 1 vagrant vagrant  629 May 26 08:47 phpunit.xml
drwxrwxrwx 1 vagrant vagrant    0 May 26 08:47 public
-rwxrwxrwx 1 vagrant vagrant  266 May 26 08:47 README.md
-rwxrwxrwx 1 vagrant vagrant  560 May 26 08:47 server.php
drwxrwxrwx 1 vagrant vagrant 4096 May 26 08:47 storage
drwxrwxrwx 1 vagrant vagrant    0 May 26 08:47 tests
drwxrwxrwx 1 vagrant vagrant 8192 May 26 09:18 vendor
vagrant@homestead:/vagrant/code/pyrocms/alpha2$
vagrant@homestead:/vagrant/code/pyrocms/alpha2$
vagrant@homestead:/vagrant/code/pyrocms/alpha2$ ls
addons   bin        composer.json    core         package.json  README.md   tests
app      bootstrap  config           database     phpunit.xml   server.php  vendor
artisan  build.xml  CONTRIBUTING.md  Gulpfile.js  public        storage
vagrant@homestead:/vagrant/code/pyrocms/alpha2$ vim composer.json
vagrant@homestead:/vagrant/code/pyrocms/alpha2$ vim composer.json
vagrant@homestead:/vagrant/code/pyrocms/alpha2$ rm -rf ~/.composer/cache/
vagrant@homestead:/vagrant/code/pyrocms/alpha2$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing anomaly/dashboard-module (dev-master 237e300)
    Downloading: 100%
    Failed to download anomaly/dashboard-module from dist: Could not delete core/ano
maly/dashboard-module/ebd60b9ac0d4f6b06fd5313196e584d9:
    Now trying to download from source
  - Installing anomaly/dashboard-module (dev-master 237e300)
    Cloning 237e300ea25cb8b3ce466610d47a154adcf53f6a
    237e300ea25cb8b3ce466610d47a154adcf53f6a is gone (history was rewritten?)



  [RuntimeException]
  Failed to execute git checkout '237e300ea25cb8b3ce466610d47a154adcf53f6a' -- &&
   git reset --hard '237e300ea25cb8b3ce466610d47a154adcf53f6a'
  Note: checking out '237e300ea25cb8b3ce466610d47a154adcf53f6a'.
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:
    git checkout -b new_branch_name
  HEAD is now at 237e300... Prevent array
  error: unable to create file resources/js/highcharts/exporting-server/java/high
  charts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classe
  s/com/highcharts/export/controller/ExportController.class (Operation not permit
  ted)
  error: unable to create file resources/js/highcharts/exporting-server/java/high
  charts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classe
  s/com/highcharts/export/controller/ZeroRequestParameterException.class (Operati
  on not permitted)
  error: unable to create file resources/js/highcharts/exporting-server/java/high
  charts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classe
  s/com/highcharts/export/interceptor/RequestInterceptor.class (Operation not per
  mitted)
  fatal: Could not reset index file to revision '237e300ea25cb8b3ce466610d47a154a
  dcf53f6a'.

**Comment by RyanThompson** [comment]
jacksun are you having composer auto load issues or permissions issues? Your log there looks like failure to write type stuff.

**Comment by samharrison7** [comment]
I'm getting a similar (but not identical) error on composer install:

    Loading composer repositories with package information
    Installing dependencies (including require-dev)
      - Installing anomaly/dashboard-module (dev-master 237e300)
        Cloning 237e300ea25cb8b3ce466610d47a154adcf53f6a
        237e300ea25cb8b3ce466610d47a154adcf53f6a is gone (history was rewritten?)
        Failed to download anomaly/dashboard-module from source: Failed to execute g
    it checkout "237e300ea25cb8b3ce466610d47a154adcf53f6a" -- && git reset --hard "2
    37e300ea25cb8b3ce466610d47a154adcf53f6a"
    
    Note: checking out '237e300ea25cb8b3ce466610d47a154adcf53f6a'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b new_branch_name
    
    HEAD is now at 237e300... Prevent array
    error: unable to create file resources/js/highcharts/exporting-server/java/highc
    harts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classes/
    com/highcharts/export/controller/ZeroRequestParameterException.class (No such fi
    le or directory)
    fatal: Could not reset index file to revision '237e300ea25cb8b3ce466610d47a154ad
    cf53f6a'.
    
        Now trying to download from dist
      - Installing anomaly/dashboard-module (dev-master 237e300)
        Downloading: 100%
    
      [ErrorException]
      ZipArchive::extractTo(C:\xampp\htdocs\pyro-test\pyrocms/vendor/composer/014
      834bb/anomalylabs-dashboard-module-237e300\resources\js\highcharts\exportin
      g-server\java\highcharts-export\highcharts-export-convert\target\classes\co
      m\highcharts\export\converter/SVGConverterException.class): failed to open
      stream: Invalid argument
    
    install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-p
    lugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress
    ] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [pac
    kages1] ... [packagesN]
    
The difference being I get "No such file or directory" as opposed to "Operation not permitted" when it fails to create ZeroRequestParameterException.class. Any thoughts?

**Comment by sandrobocon** [comment]
Just for test purpose, I removed from composer.json dashboard-module. It installs everything, except these files. I believe is some kind of access permission, alias or flag used on them. But couldn't find out until now.

**Comment by RyanThompson** [comment]
Thanks for the info! Ill look into it this afternoon.

**Comment by jnico** [comment]
Ryan, same identical problem as @samharrison7 on win. I moved line anomaly/dashboard-module to the bottom of require then the everything finished loading in, except when getting to the require; dashboard-module: ~1.0 again it downloads zip to cache then disappears when unzip, then throws error.
```

  - Installing anomaly/files-module (v1.0.7)
    Loading from cache

  - Installing anomaly/contact-plugin (v1.0.1)
    Loading from cache

  - Installing anomaly/helper-plugin (v1.0.1)
    Loading from cache

  - Installing anomaly/anomaly-theme (v1.0.3)
    Loading from cache

  - Installing anomaly/starter-theme (v1.0.3)
    Loading from cache

 - Installing anomaly/dashboard-module (v1.0.2)
    Downloading: 100%

  [ErrorException]
  ZipArchive::extractTo(C:\pyrocms/vendor/composer/4226ccad/anomalylabs-dashb
  oard-module-dac21e6\resources\js\highcharts\exporting-server\java\highchart
  s-export\highcharts-export-web\target\highcharts-export-web\WEB-INF\classes
  \com\highcharts\export\controller/ExportController.class): failed to open s
  tream: Invalid argument


```

**Comment by RyanThompson** [comment]
You need to do --prefer-source instead - that whatnot doesn't have to unzip

**Comment by jnico** [comment]
done. loaded complete.

**Comment by RyanThompson** [comment]
Excellent!

**Comment by Vishnja** [comment]
Doesn't work on Windows (no Homestead). Gives the same error. With --prefer-source and after 'composer clear-cache'.
